# Generated by Django 3.0.1 on 2020-01-11 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Обо мне')),
                ('img', models.ImageField(upload_to='media', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Обо мне',
                'verbose_name_plural': 'Обо мне',
            },
        ),
        migrations.CreateModel(
            name='Caruosel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Картинка')),
                ('number', models.IntegerField(verbose_name='Номер слайда')),
            ],
            options={
                'verbose_name': 'Слайд в слайдер',
                'verbose_name_plural': 'Слайды в слайдер',
            },
        ),
        migrations.CreateModel(
            name='link_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип ссылки',
                'verbose_name_plural': 'Тип ссылок',
            },
        ),
        migrations.CreateModel(
            name='link_uch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Ссылка_Меню',
                'verbose_name_plural': 'Ссылки_Меню',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Картинка')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('pub_date', models.DateField(verbose_name='Дата')),
                ('label', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Картинка')),
                ('name', models.CharField(max_length=15, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.link_Type')),
            ],
            options={
                'verbose_name': 'Ссылка(доп.)',
                'verbose_name_plural': 'Ссылки(доп.)',
            },
        ),
    ]
