# Generated by Django 3.0.1 on 2020-01-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_liberi_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_me',
            name='img',
        ),
    ]
