# Generated by Django 3.0.1 on 2020-01-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_about_me_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
