# Generated by Django 3.0.1 on 2020-01-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('pub_date', models.DateField(verbose_name='Дата')),
                ('label', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Пост алгебра',
                'verbose_name_plural': 'Посты алгебра',
            },
        ),
        migrations.CreateModel(
            name='Post_g',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('pub_date', models.DateField(verbose_name='Дата')),
                ('label', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Пост геометрия',
                'verbose_name_plural': 'Посты геометрия',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
